# Generated by Django 2.2.1 on 2019-05-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSeccion', models.CharField(max_length=50, verbose_name='Ingrese Nombre Seccion')),
            ],
            options={
                'verbose_name': 'SeccionNoticia',
                'verbose_name_plural': 'SeccionNoticias',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=None, verbose_name='Imagen Noticia')),
                ('titulo', models.CharField(max_length=50, verbose_name='Ingrese Titulo Noticia')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo_Noticia')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.SeccionNoticia', verbose_name='Seccion Noticia')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
