# Generated by Django 2.2.1 on 2019-05-16 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20190516_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
