# Generated by Django 2.2.1 on 2019-05-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20190517_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(verbose_name='Cuerpo Noticia'),
        ),
    ]
