# Generated by Django 2.2.1 on 2019-05-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20190517_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticia'},
        ),
    ]
