# Generated by Django 2.2.1 on 2019-05-30 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_auto_20190518_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-creado'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticia'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(verbose_name='Cuerpo Noticia'),
        ),
    ]
